spring:
  application:
    name: aiService

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/fitness-recommendations}
      database: ${MONGO_DB:fitness-recommendations}

  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

server:
  port: ${PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

rabbitmq:
  exchange:
    name: ${RB_EXCHANGE:fitness.exchange}
  queue:
    name: ${RB_QUEUE:activity.queue}
  routing:
    key: ${RB_ROUTING_KEY:activity.tracking}

gemini:
  api:
    url: ${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=}
    key: ${GEMINI_KEY}
