spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/fitness-oauth2/protocol/openid-connect/certs



  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/users/**

            - id: activity-service
              uri: lb://ACTIVITYSERVICE
              predicates:
                - Path=/api/activities/**

            - id: ai-service
              uri: lb://AISERVICE
              predicates:
                - Path=/api/recommendations/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
