spring:
  application:
    name: aiService

  data:
    mongodb:
      uri: mongodb://mongodb:27017/fitness-recommendations
      database: fitness-recommendations

    rabbitmq:
      host: rabbitmq
      port: 5672
      username: guest
      password: guest

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key="
    key: "AIzaSyCjqsN_QURPb902LJlakoP4_f2YjsiJpuk"
